source:      .
destination: ./_site
layouts_dir: ./_layouts
data_dir:    ./_data

# Handling Reading
redirects:    yes
safe:         false
include:      [".htaccess", "_pages"]
exclude:      [./_drafts/]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
gems:
# Atom (RSS) feeds for GitHub Pages
# https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-feed
# Search engine optimization for GitHub Pages
# https://help.github.com/articles/search-engine-optimization-for-github-pages/
  - jekyll-seo-tag
# Redirect visitors to the updated URL
# https://help.github.com/articles/redirects-on-github-pages/
  - jekyll-redirect-from

# Conversion
markdown:    kramdown
# https://github.com/jneen/rouge
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

# Serving
detach:  false
port:    4001
host:    0.0.0.0
#host:    127.0.0.1
# For projects, use the baseurl to set host/[baseurl]/
# http://blog.parkermoore.de/2014/04/27/clearing-up-confusion-around-baseurl/
# baseurl: "/project" # does not include hostname
baseurl: ""

# Backwards-compatibility
relative_permalinks: false

# Outputting
permalink:     none
paginate_path: /page:num
timezone:      null

quiet:    false
defaults: []

sass:
  sass_dir:      _sass
  style:         expanded    # [nested|expanded|compact|compressed]
#  deploy_style: compressed  # [nested|expanded|compact|compressed]

# Setup
title:          "Duterte Times"
tagline:        "The times, they are a-changin'"
description:    "Philippine alternative social news website"
url:            https://dutertetimes.github.io
image_source:   https://dl.dropboxusercontent.com/u/47611946/dutertetimes

#og_image:       /site/dutertetimes_default_fb_post_image.png
og_image:       /site/fb_post_thumbnail_vertical_01.1.png
fb_app_id:      167022237037290
fb_admins:      167022237037290
fb_publisher:   167022237037290
fb_url:         https://www.facebook.com/dutertetimes2016/

author:
  name:         'dutertetimes'
  icon:         dutertetimes.png
  github:       http://github.com/dutertetimes
  #wordpress:   http://dutertetimes.wordpress.com/
  
defaults:
  -
    scope:
      path:     "/*.md" # "" means all files in the project
      type:     "pages" # [posts|pages|drafts]
    values:
      layout:   "default"
  -
    scope:
      path:     "posts" # "" means all files in the project
      type:     "posts" # [posts|pages|drafts]
    values:
      layout:   "post"

# Custom vars
version:        0.1.0
